@startuml

cloud Cloud {
    node TravisCI
    node Vagrant
    node vagrantlibvrt
    node libvrt
    node KVM

    TravisCI -> Vagrant
    Vagrant -> vagrantlibvrt
    vagrantlibvrt -> libvrt
    libvrt -> KVM
}

@enduml